baseURL: "https://viable.blog/"
languageCode: "en-gb"
title: "The Viable Blog"
pygmentsUseClasses: true

permalinks:
  posts: /posts/:filename/

outputs:
  home:
    - HTML
  post:
    - HTML
    - RSS